-- ============================================================
-- 034_hnsw_iterative_scan.sql — **적용하지 않음 (2026-09-15 실측 기록)**
-- ============================================================
-- 이 파일은 실행하지 말 것. 아래 설정을 운영에 넣었다가 되돌린 기록이다.
--
-- 목적이었던 것
--   dense 후보 부족: HNSW 후보(hnsw.ef_search 기본 40)에서 (flags->>'filtered_reason') IS NULL 로
--   40.9% 가 걸러져 top_k 50 요청에 25~41개만 온다(실제 벡터 기준 브루트포스 대비 41/50).
--
-- 시도 → 결과 (운영 API 실측, 2026-09-15 17:20~17:40 KST)
--   1. ALTER DATABASE SET hnsw.iterative_scan='relaxed_order' + hnsw.ef_search=100
--      - 권한: 같은 세션에서 벡터 연산으로 vector.so 를 먼저 로드해야 42501 이 안 난다.
--      - DB 직접 호출(LIMIT 리터럴)은 50/50, 20ms 로 좋았다.
--      - 그러나 API: hybrid 는 dense 후보 26→49 로 좋아지고 0.24s 인데, **dense 전용 모드가 1.0s → 10~14s**.
--        Edge 가 PostgREST 로 top_k 를 바인드 파라미터로 넘겨 generic plan 이 LIMIT 을 모른 채
--        HNSW 경로 비용(ef·iterative 로 상승)을 Seq Scan 보다 높게 봐 계획이 뒤집힌다.
--   2. iterative_scan 만 되돌리고 ef_search=100 유지 → dense 전용 여전히 10s (hits 76).
--   3. plan_cache_mode=force_custom_plan 추가 → dense 전용 10s 그대로, hybrid 는 1.7~3.1s 로 악화,
--      풀 연결마다 설정이 섞여 후보 수가 흔들림(25↔49).
--   4. 전부 RESET → dense 0.9s, hybrid 1.0s (034 이전 기준선). **이 상태로 둔다.**
--
-- 결론
--   DB 수준 GUC 로는 못 푼다. 근본 원인은 "LIMIT 이 Param 인 SQL 함수 + pgvector 비용 모델" 이라
--   코드 쪽 후속이 필요하다. 후보: ① Edge 가 쓰는 top_k 값(50/100/200)별로 LIMIT 리터럴 함수를 두기
--   ② ablation 전용 dense 모드 폐기 ③ 함수 내부에서 top_k 를 CASE 로 상수화. 골든셋(120행 top-1 77.5%)
--   재측정과 함께 별도 작업으로.
--
-- 참고: 벤치에서 벡터를 서브쿼리로 넘기면 함수 인라인이 막혀(contain_subplans) 같은 Seq Scan 경로를
--   밟는다 — 측정할 땐 벡터를 리터럴로 넣을 것. ALTER FUNCTION ... SET 도 proconfig 때문에 인라인을
--   막으므로 금지.
-- ============================================================
-- (실행할 SQL 없음)

-- ------------------------------------------------------------
-- 추기 (2026-09-16 01:58 KST) — **hnsw.ef_search=100 만 다시 적용, 이번엔 유지**
-- ------------------------------------------------------------
-- 036(halfvec, 인덱스 265MB→25MB) 뒤에 같은 실험을 다시 했다. 상황이 달라졌다: 인덱스가 shared_buffers 안에
-- 들어가고 죽은 엔트리가 0 이라 HNSW 경로 비용이 낮게 잡혀 generic plan 이 뒤집히지 않는다.
--   적용:  select '[1,2]'::vector <-> '[1,2]'::vector;  -- vector.so 선로드
--          alter database postgres set hnsw.ef_search = 100;
--   iterative_scan 은 건드리지 않았다(2026-09-15 의 10s 악화 원인이라 §5 규칙으로 금지).
--   실측(골든 120행 × 3모드, 적용 전→후):
--     hybrid top-1 99/120 → 99/120, avg 246 → 217ms
--     dense  top-1 100/120 → 100/120, avg 158 → 231ms (max 323 → 1,917ms 1건, 콜드)
--     sparse 54/120 → 54/120
--     PostgREST rpc search_dense_only(top_k 50): 행수 40~41 → **50**, 웜 57~78ms. dense 전용 10s 재현 없음.
--   되돌리기: alter database postgres reset hnsw.ef_search;  (같은 세션에서 벡터 연산 선행)
--   조건: 인덱스가 다시 110MB 를 넘으면(docs/ops/db-write-control.md §1) 이 설정부터 의심한다.
